version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: large
    steps:
      - checkout

      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: go get -v -t -d ./...
      - run: ./cc-test-reporter before-build
      - run:
          command: ./dockertest.sh
          no_output_timeout: 20m
      - run: ./cc-test-reporter after-build -p $(go list -m) --exit-code $?
      - run: bash <(curl -s https://codecov.io/bash)